kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "superseriousbusiness/gotosocial:0.12.2"

[env]
   GTS_LOG_TIMESTAMP_FORMAT = "2006-01-02T15:04:05.999999999Z07:00"
   GTS_LANDING_PAGE_USER = "mfjt"
   GTS_HOST = "gts.mfjt.jp"
   GTS_ACCOUNT_DOMAIN = "mfjt.jp"
   GTS_TRUSTED_PROXIES = "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,66.241.124.9,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,::1,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
   GTS_INSTANCE_LANGUAGES = "ja-jp"
   GTS_ACCOUNTS_REGISTRATION_OPEN = "false"
   GTS_STORAGE_BACKEND = "s3"
   GTS_STORAGE_S3_PROXY = "true"
   GTS_REQUEST_ID_HEADER = "Fly-Request-Id"
   TZ = "Asia/Tokyo"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
