name: Fly Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: >
          flyctl deploy --remote-only
          -a ${{ vars.APP }}
          -e GTS_DB_ADDRESS=${{ vars.GTS_DB_ADDRESS }}
          -e GTS_DB_USER=${{ vars.GTS_DB_USER }}
          -e GTS_STORAGE_S3_ACCESS_KEY=${{ vars.GTS_STORAGE_S3_ACCESS_KEY }}
          -e GTS_STORAGE_S3_BUCKET=${{ vars.GTS_STORAGE_S3_BUCKET }}
          -e GTS_STORAGE_S3_ENDPOINT=${{ vars.GTS_STORAGE_S3_ENDPOINT }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
